dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - pip install codecov
install:
  - "rm -rf dist/*"
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl
script:
  - cd tests/ && nosetests --with-coverage --cover-package jmespath .
  - if [[ $TRAVIS_PYTHON_VERSION != '3.8' ]]; then JP_MAX_EXAMPLES=10000 nosetests ../extra/test_hypothesis.py; fi
after_success:
  - codecov
